version: '3.8'

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  mongo_seed:
    build:
      context: ./api/src/mongo-seed
      dockerfile: Dockerfile
    container_name: mongo_seed
    depends_on:
      - mongodb

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - '2181:2181'

  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: 'area-topic:1:1'
    depends_on:
      - zookeeper
    healthcheck:
      test: nc -z localhost 9092 || exit -1
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10

  geo-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: geo-api
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      mongo_seed:
        condition: service_completed_successfully
      kafka:
        condition: service_healthy
